name: SonarCloud Analysis

on:
  pull_request:
    branches:
      - main

jobs:
  sonarcloud:
    uses: TheHiddenCargo/SonarCloud-PipelineIntegration/.github/workflows/sonarcloud-analysis.yml@v0.1.3
    with:
      node-version: '18'
      branch-name: 'main'
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      SONAR_ORGANIZATION: ${{ secrets.SONAR_ORGANIZATION }}
      SONAR_PROJECT_KEY: ${{ secrets.SONAR_PROJECT_KEY }}
